.PHONY: clean All

All:
	@echo "----------Building project:[ plugin - Release ]----------"
	@"$(MAKE)" -f  "plugin.mk"
clean:
	@echo "----------Cleaning project:[ plugin - Release ]----------"
	@"$(MAKE)" -f  "plugin.mk" clean
